---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set environment variables
        run: |
          echo "DB_HOST=${{ vars.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ vars.DB_NAME }}" >> $GITHUB_ENV
          echo "DB_USER=${{ vars.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASS=${{ vars.DB_PASS }}" >> $GITHUB_ENV

      - name: Run Test
        run: |
          docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

      - name: Lint
        run: |
          docker compose run --rm app sh -c "flake8"
